<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('INSCRICAO', 'doctrine');

/**
 * BaseINSCRICAO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_inscricao
 * @property integer $id_vestibular_curso
 * @property integer $id_sala
 * @property string $nm_vestibulando
 * @property string $te_endereco
 * @property integer $nu_numero
 * @property string $nu_cpf
 * @property string $te_complemento
 * @property string $te_bairro
 * @property string $sg_estado
 * @property string $te_cidade
 * @property string $nu_fone
 * @property string $te_resultado
 * @property float $nu_pontuacao
 * @property date $dt_inscricao
 * @property SALA $SALA
 * @property VESTIBULARCURSO $VESTIBULARCURSO
 * 
 * @method integer         getIdInscricao()         Returns the current record's "id_inscricao" value
 * @method integer         getIdVestibularCurso()   Returns the current record's "id_vestibular_curso" value
 * @method integer         getIdSala()              Returns the current record's "id_sala" value
 * @method string          getNmVestibulando()      Returns the current record's "nm_vestibulando" value
 * @method string          getTeEndereco()          Returns the current record's "te_endereco" value
 * @method integer         getNuNumero()            Returns the current record's "nu_numero" value
 * @method string          getNuCpf()               Returns the current record's "nu_cpf" value
 * @method string          getTeComplemento()       Returns the current record's "te_complemento" value
 * @method string          getTeBairro()            Returns the current record's "te_bairro" value
 * @method string          getSgEstado()            Returns the current record's "sg_estado" value
 * @method string          getTeCidade()            Returns the current record's "te_cidade" value
 * @method string          getNuFone()              Returns the current record's "nu_fone" value
 * @method string          getTeResultado()         Returns the current record's "te_resultado" value
 * @method float           getNuPontuacao()         Returns the current record's "nu_pontuacao" value
 * @method date            getDtInscricao()         Returns the current record's "dt_inscricao" value
 * @method SALA            getSALA()                Returns the current record's "SALA" value
 * @method VESTIBULARCURSO getVESTIBULARCURSO()     Returns the current record's "VESTIBULARCURSO" value
 * @method INSCRICAO       setIdInscricao()         Sets the current record's "id_inscricao" value
 * @method INSCRICAO       setIdVestibularCurso()   Sets the current record's "id_vestibular_curso" value
 * @method INSCRICAO       setIdSala()              Sets the current record's "id_sala" value
 * @method INSCRICAO       setNmVestibulando()      Sets the current record's "nm_vestibulando" value
 * @method INSCRICAO       setTeEndereco()          Sets the current record's "te_endereco" value
 * @method INSCRICAO       setNuNumero()            Sets the current record's "nu_numero" value
 * @method INSCRICAO       setNuCpf()               Sets the current record's "nu_cpf" value
 * @method INSCRICAO       setTeComplemento()       Sets the current record's "te_complemento" value
 * @method INSCRICAO       setTeBairro()            Sets the current record's "te_bairro" value
 * @method INSCRICAO       setSgEstado()            Sets the current record's "sg_estado" value
 * @method INSCRICAO       setTeCidade()            Sets the current record's "te_cidade" value
 * @method INSCRICAO       setNuFone()              Sets the current record's "nu_fone" value
 * @method INSCRICAO       setTeResultado()         Sets the current record's "te_resultado" value
 * @method INSCRICAO       setNuPontuacao()         Sets the current record's "nu_pontuacao" value
 * @method INSCRICAO       setDtInscricao()         Sets the current record's "dt_inscricao" value
 * @method INSCRICAO       setSALA()                Sets the current record's "SALA" value
 * @method INSCRICAO       setVESTIBULARCURSO()     Sets the current record's "VESTIBULARCURSO" value
 * 
 * @package    ProjetoUnice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseINSCRICAO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('INSCRICAO');
        $this->hasColumn('id_inscricao', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_vestibular_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_sala', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nm_vestibulando', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('te_endereco', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('nu_numero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nu_cpf', 'string', 11, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 11,
             ));
        $this->hasColumn('te_complemento', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('te_bairro', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('sg_estado', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('te_cidade', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('nu_fone', 'string', 12, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 12,
             ));
        $this->hasColumn('te_resultado', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('nu_pontuacao', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('dt_inscricao', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SALA', array(
             'local' => 'id_sala',
             'foreign' => 'id_sala',
             'onDelete' => 'CASCADE'));

        $this->hasOne('VESTIBULARCURSO', array(
             'local' => 'id_vestibular_curso',
             'foreign' => 'id_vestibular_curso',
             'onDelete' => 'CASCADE'));
    }
}