<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VESTIBULARCURSO', 'doctrine');

/**
 * BaseVESTIBULARCURSO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_vestibular_curso
 * @property integer $id_vestibular
 * @property integer $id_curso
 * @property float $nu_concorrencia
 * @property integer $qt_vagas
 * @property float $nu_pontuacao
 * @property integer $nu_inscritos
 * @property VESTIBULAR $VESTIBULAR
 * @property CURSO $CURSO
 * @property Doctrine_Collection $INSCRICAO
 * 
 * @method integer             getIdVestibularCurso()   Returns the current record's "id_vestibular_curso" value
 * @method integer             getIdVestibular()        Returns the current record's "id_vestibular" value
 * @method integer             getIdCurso()             Returns the current record's "id_curso" value
 * @method float               getNuConcorrencia()      Returns the current record's "nu_concorrencia" value
 * @method integer             getQtVagas()             Returns the current record's "qt_vagas" value
 * @method float               getNuPontuacao()         Returns the current record's "nu_pontuacao" value
 * @method integer             getNuInscritos()         Returns the current record's "nu_inscritos" value
 * @method VESTIBULAR          getVESTIBULAR()          Returns the current record's "VESTIBULAR" value
 * @method CURSO               getCURSO()               Returns the current record's "CURSO" value
 * @method Doctrine_Collection getINSCRICAO()           Returns the current record's "INSCRICAO" collection
 * @method VESTIBULARCURSO     setIdVestibularCurso()   Sets the current record's "id_vestibular_curso" value
 * @method VESTIBULARCURSO     setIdVestibular()        Sets the current record's "id_vestibular" value
 * @method VESTIBULARCURSO     setIdCurso()             Sets the current record's "id_curso" value
 * @method VESTIBULARCURSO     setNuConcorrencia()      Sets the current record's "nu_concorrencia" value
 * @method VESTIBULARCURSO     setQtVagas()             Sets the current record's "qt_vagas" value
 * @method VESTIBULARCURSO     setNuPontuacao()         Sets the current record's "nu_pontuacao" value
 * @method VESTIBULARCURSO     setNuInscritos()         Sets the current record's "nu_inscritos" value
 * @method VESTIBULARCURSO     setVESTIBULAR()          Sets the current record's "VESTIBULAR" value
 * @method VESTIBULARCURSO     setCURSO()               Sets the current record's "CURSO" value
 * @method VESTIBULARCURSO     setINSCRICAO()           Sets the current record's "INSCRICAO" collection
 * 
 * @package    ProjetoUnice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVESTIBULARCURSO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('VESTIBULARCURSO');
        $this->hasColumn('id_vestibular_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_vestibular', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nu_concorrencia', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('qt_vagas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nu_pontuacao', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('nu_inscritos', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('VESTIBULAR', array(
             'local' => 'id_vestibular',
             'foreign' => 'id_vestibular',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CURSO', array(
             'local' => 'id_curso',
             'foreign' => 'id_curso',
             'onDelete' => 'CASCADE'));

        $this->hasMany('INSCRICAO', array(
             'local' => 'id_vestibular_curso',
             'foreign' => 'id_vestibular_curso'));
    }
}