<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SALA', 'doctrine');

/**
 * BaseSALA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_sala
 * @property string $nm_sala
 * @property integer $qt_max_suportada
 * @property Doctrine_Collection $INSCRICAO
 * 
 * @method integer             getIdSala()           Returns the current record's "id_sala" value
 * @method string              getNmSala()           Returns the current record's "nm_sala" value
 * @method integer             getQtMaxSuportada()   Returns the current record's "qt_max_suportada" value
 * @method Doctrine_Collection getINSCRICAO()        Returns the current record's "INSCRICAO" collection
 * @method SALA                setIdSala()           Sets the current record's "id_sala" value
 * @method SALA                setNmSala()           Sets the current record's "nm_sala" value
 * @method SALA                setQtMaxSuportada()   Sets the current record's "qt_max_suportada" value
 * @method SALA                setINSCRICAO()        Sets the current record's "INSCRICAO" collection
 * 
 * @package    ProjetoUnice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSALA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('SALA');
        $this->hasColumn('id_sala', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nm_sala', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('qt_max_suportada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('INSCRICAO', array(
             'local' => 'id_sala',
             'foreign' => 'id_sala'));
    }
}