<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CURSO', 'doctrine');

/**
 * BaseCURSO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_curso
 * @property string $nm_curso
 * @property string $te_cargahoraria
 * @property string $sg_flag
 * @property Doctrine_Collection $VESTIBULARCURSO
 * 
 * @method integer             getIdCurso()         Returns the current record's "id_curso" value
 * @method string              getNmCurso()         Returns the current record's "nm_curso" value
 * @method string              getTeCargahoraria()  Returns the current record's "te_cargahoraria" value
 * @method string              getSgFlag()          Returns the current record's "sg_flag" value
 * @method Doctrine_Collection getVESTIBULARCURSO() Returns the current record's "VESTIBULARCURSO" collection
 * @method CURSO               setIdCurso()         Sets the current record's "id_curso" value
 * @method CURSO               setNmCurso()         Sets the current record's "nm_curso" value
 * @method CURSO               setTeCargahoraria()  Sets the current record's "te_cargahoraria" value
 * @method CURSO               setSgFlag()          Sets the current record's "sg_flag" value
 * @method CURSO               setVESTIBULARCURSO() Sets the current record's "VESTIBULARCURSO" collection
 * 
 * @package    ProjetoUnice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCURSO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CURSO');
        $this->hasColumn('id_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nm_curso', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('te_cargahoraria', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('sg_flag', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VESTIBULARCURSO', array(
             'local' => 'id_curso',
             'foreign' => 'id_curso'));
    }
}