<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('INSTITUICAO', 'doctrine');

/**
 * BaseINSTITUICAO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_instituicao
 * @property string $nm_instituicao
 * @property string $te_endereco
 * @property integer $nu_numero
 * @property string $te_complemento
 * @property string $te_bairro
 * @property string $te_cidade
 * @property string $sg_estado
 * @property string $nu_cnpj
 * @property string $nu_fone
 * 
 * @method integer     getIdInstituicao()  Returns the current record's "id_instituicao" value
 * @method string      getNmInstituicao()  Returns the current record's "nm_instituicao" value
 * @method string      getTeEndereco()     Returns the current record's "te_endereco" value
 * @method integer     getNuNumero()       Returns the current record's "nu_numero" value
 * @method string      getTeComplemento()  Returns the current record's "te_complemento" value
 * @method string      getTeBairro()       Returns the current record's "te_bairro" value
 * @method string      getTeCidade()       Returns the current record's "te_cidade" value
 * @method string      getSgEstado()       Returns the current record's "sg_estado" value
 * @method string      getNuCnpj()         Returns the current record's "nu_cnpj" value
 * @method string      getNuFone()         Returns the current record's "nu_fone" value
 * @method INSTITUICAO setIdInstituicao()  Sets the current record's "id_instituicao" value
 * @method INSTITUICAO setNmInstituicao()  Sets the current record's "nm_instituicao" value
 * @method INSTITUICAO setTeEndereco()     Sets the current record's "te_endereco" value
 * @method INSTITUICAO setNuNumero()       Sets the current record's "nu_numero" value
 * @method INSTITUICAO setTeComplemento()  Sets the current record's "te_complemento" value
 * @method INSTITUICAO setTeBairro()       Sets the current record's "te_bairro" value
 * @method INSTITUICAO setTeCidade()       Sets the current record's "te_cidade" value
 * @method INSTITUICAO setSgEstado()       Sets the current record's "sg_estado" value
 * @method INSTITUICAO setNuCnpj()         Sets the current record's "nu_cnpj" value
 * @method INSTITUICAO setNuFone()         Sets the current record's "nu_fone" value
 * 
 * @package    ProjetoUnice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseINSTITUICAO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('INSTITUICAO');
        $this->hasColumn('id_instituicao', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nm_instituicao', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('te_endereco', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('nu_numero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('te_complemento', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('te_bairro', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('te_cidade', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('sg_estado', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('nu_cnpj', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('nu_fone', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}