<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/12/04 16:04:58
return array(

  // sfJQueryUIPlugin_module_libs

  // sfJQueryUIPlugin_lib
  'sfwidgetformdatejqueryui' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/sfJQueryUIPlugin/lib/widget/sfWidgetFormDateJQueryUI.class.php',

  // brFormExtraPlugin_module_libs
  'br_cep/basebr_cepactions' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/modules/br_cep/lib/Basebr_cepActions.class.php',
  'br_form_extra_demo/basebr_form_extra_demoactions' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/modules/br_form_extra_demo/lib/Basebr_form_extra_demoActions.class.php',

  // brFormExtraPlugin_lib
  'sfwidgetformchoiceufbr' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/widget/sfWidgetFormChoiceUFBR.class.php',
  'sfwidgetforminputcep' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/widget/sfWidgetFormInputCep.class.php',
  'sfwidgetformselectcheckboxstates' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/widget/sfWidgetFormSelectCheckboxStates.class.php',
  'sfvalidatorchoicestates' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/validator/sfValidatorChoiceStates.class.php',
  'sfvalidatorcep' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/validator/sfValidatorCep.class.php',
  'sfvalidatori18ndate' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/validator/i18n/sfValidatori18nDate.class.php',
  'sfvalidatorcpfcnpj' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/validator/sfValidatorCpfCnpj.class.php',
  'plugincep_braziltable' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/model/doctrine/PluginCEP_BrazilTable.class.php',
  'plugincep_brazil' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/plugins/brFormExtraPlugin/lib/model/doctrine/PluginCEP_Brazil.class.php',

  // sfJqueryReloadedPlugin_module_libs

  // sfJqueryReloadedPlugin_lib

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrineexception' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sftesterdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfwebdebugpaneldoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfwidgetformdoctrinechoice' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrinecli' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfformdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'swift_doctrinespool' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinegenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformgenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinerecordi18nfilter' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfvalidatordoctrinechoice' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinedqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrineinsertsqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinecreatemodeltables' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedataloadtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildschematask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildformstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinedropdbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebuilddbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinedatadumptask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinebuildfilterstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinebuildsqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinebasetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinemigratetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinepager' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineconnectionlistener' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineroutecollection' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',

  // project
  'baseform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/BaseForm.class.php',
  'cursoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/CURSOForm.class.php',
  'vestibularcursoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/VESTIBULARCURSOForm.class.php',
  'baseinscricaoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/base/BaseINSCRICAOForm.class.php',
  'basecursoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/base/BaseCURSOForm.class.php',
  'basesalaform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/base/BaseSALAForm.class.php',
  'basevestibularform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/base/BaseVESTIBULARForm.class.php',
  'baseinstituicaoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/base/BaseINSTITUICAOForm.class.php',
  'basevestibularcursoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/base/BaseVESTIBULARCURSOForm.class.php',
  'vestibularform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/VESTIBULARForm.class.php',
  'instituicaoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/INSTITUICAOForm.class.php',
  'inscricaoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/INSCRICAOForm.class.php',
  'baseformdoctrine' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/BaseFormDoctrine.class.php',
  'inscricaopontuacaoform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/INSCRICAOPONTUACAOForm.class.php',
  'cursosvestibularform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/CursosVestibularForm.class.php',
  'salaform' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/form/doctrine/SALAForm.class.php',
  'vestibularformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/VESTIBULARFormFilter.class.php',
  'inscricaoformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/INSCRICAOFormFilter.class.php',
  'basevestibularformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/base/BaseVESTIBULARFormFilter.class.php',
  'basecursoformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/base/BaseCURSOFormFilter.class.php',
  'baseinstituicaoformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/base/BaseINSTITUICAOFormFilter.class.php',
  'basesalaformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/base/BaseSALAFormFilter.class.php',
  'basevestibularcursoformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/base/BaseVESTIBULARCURSOFormFilter.class.php',
  'baseinscricaoformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/base/BaseINSCRICAOFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'salaformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/SALAFormFilter.class.php',
  'cursoformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/CURSOFormFilter.class.php',
  'instituicaoformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/INSTITUICAOFormFilter.class.php',
  'vestibularcursoformfilter' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/filter/doctrine/VESTIBULARCURSOFormFilter.class.php',

  // project_model
  'sala' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/SALA.class.php',
  'baseinscricao' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/base/BaseINSCRICAO.class.php',
  'basevestibularcurso' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/base/BaseVESTIBULARCURSO.class.php',
  'basesala' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/base/BaseSALA.class.php',
  'basevestibular' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/base/BaseVESTIBULAR.class.php',
  'baseinstituicao' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/base/BaseINSTITUICAO.class.php',
  'basecurso' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/base/BaseCURSO.class.php',
  'salatable' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/SALATable.class.php',
  'inscricao' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/INSCRICAO.class.php',
  'instituicao' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/INSTITUICAO.class.php',
  'instituicaotable' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/INSTITUICAOTable.class.php',
  'vestibularcursotable' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/VESTIBULARCURSOTable.class.php',
  'curso' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/CURSO.class.php',
  'cursotable' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/CURSOTable.class.php',
  'vestibulartable' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/VESTIBULARTable.class.php',
  'inscricaotable' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/INSCRICAOTable.class.php',
  'vestibular' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/VESTIBULAR.class.php',
  'vestibularcurso' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/lib/model/doctrine/VESTIBULARCURSO.class.php',

  // application
  'myuser' => '/home/carloswherbet/Dropbox/Trabalho/desenvolvimento/ProjetoUnice/apps/frontend/lib/myUser.class.php',

  // modules
);
