<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/12/04 16:04:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sisvest',
  'username' => 'root',
  'password' => 'mysql',
  'name' => 'doctrine',
)),);
