<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/12/04 16:04:59
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
