<?php

/**
 * CURSOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CURSOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CURSOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CURSO');
    }

    public function getCursosAtivos() {
        $q = $this->createQuery('c')
            ->where('c.sg_flag = "A" or c.sg_flag = ""');

        return $q->execute();

    }


  

  

}