<?php

/**
 * INSCRICAOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class INSCRICAOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object INSCRICAOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('INSCRICAO');
    }

    public function getVestibularAberto($id_vestibular_curso ) {

        $q = $this->createQuery('a')          
          ->where('a.id_vestibular_curso = ?', $id_vestibular_curso);

        return $q->execute();

    }

    public function getInscritosVestibular($id_vestibular) {
        $q = $this->createQuery('a')
                ->leftJoin('a.VESTIBULARCURSO v')
                ->where('v.id_vestibular = ?', $id_vestibular )
                ->orderBy('a.dt_inscricao');

        return $q->execute();
    }

    public function getCountVestibulandosAlocados($id_vestibular) {
         $q = $this->createQuery('i')
                    ->leftJoin('i.VESTIBULARCURSO v')
                    ->where('v.id_vestibular = ?',$id_vestibular )
                    ->addWhere('i.id_sala is not null')
                    ;
         return $q->count();



     }

     public function getCountVestibulandosInscritos($id_vestibular) {
         $q = $this->createQuery('i')
                    ->leftJoin('i.VESTIBULARCURSO v')
                    ->where('v.id_vestibular = ?',$id_vestibular )
                    
                    ;
         return $q->count();



     }
}