<?php

/**
 * INSTITUICAOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class INSTITUICAOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object INSTITUICAOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('INSTITUICAO');
    }
}