<?php

/**
 * SALATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SALATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SALATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SALA');
    }
    
    public function alocarVestibulandos($id_vestibular) {
        
        $salas =  Doctrine_Core::getTable('SALA')->createQuery('a')->execute();
        // Fazendo foreach das salas onde serão inseridos os vestibulandos
         foreach ($salas as $sala) {
                // Filtrando vestibulandos do vestibular selecionado, que ainda nao foram alocados ('i.id_sala is null')
                $vestibulandos =  Doctrine_Core::getTable('INSCRICAO')
                                 ->createQuery('i')
                                 ->leftJoin('i.VESTIBULARCURSO a')
                                 ->leftJoin('a.VESTIBULAR v')
                                 ->where('v.id_vestibular = ?', $id_vestibular)
                                 ->addWhere('i.id_sala is null')
                                 ->execute();
                // Foreach dos vestibulandos
                 foreach ($vestibulandos as $vestibulando) {

                      // contando a quantidades de vestibulandos que ja foram alocados na sala do looping
                       $conte_salas = Doctrine_Query::create()
                            ->select('COUNT(1) as conte_salas, s.id_sala,s.qt_max_suportada')
                            ->from('SALA s')
                            ->innerJoin('s.INSCRICAO i')
                            ->innerJoin('i.VESTIBULARCURSO c')
                            ->innerJoin('c.VESTIBULAR v')
                            ->where('v.id_vestibular = ?',$id_vestibular )
                            ->addWhere('s.id_sala = ?',$sala->getIdSala() )
                            ->fetchArray();

                  //  echo "<pre>" ;var_dump($conte_salas[0]['qt_max_suportada']);exit;echo "</pre>" ;
                      // Se a quantidade de vestibulandos for menor que a quantidade suportada pela sala,
                      // add ele nesta sala, caso contrario nao faz nada com este vestibulando, espera prox sala.

                       if ($conte_salas[0]['conte_salas'] < $sala->getQtMaxSuportada() ) {

                                $inscricao = Doctrine::getTable('INSCRICAO')->find($vestibulando->getIdInscricao());
                                $inscricao->setIdSala($sala->getIdSala());
                                $inscricao->save();

                       }

          
                  }

           


   

         


            

         }

         return;


    }
    
}