<?php

/**
 * VESTIBULARCURSO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ProjetoUnice
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VESTIBULARCURSO extends BaseVESTIBULARCURSO
{

    public function  __toString() {

       return  "".$this->getCURSO()."";
    }
}
