<?php

/**
 * VESTIBULARTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VESTIBULARTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VESTIBULARTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VESTIBULAR');
    }
    public function getVestibularesAbertos() {
         $q = Doctrine_Core::getTable('VESTIBULAR')
            ->createQuery('a')
            ->where('sg_situacao = "A"');

         return $q->execute();
    }
   
}
