<?php

/**
 * VESTIBULARCURSOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VESTIBULARCURSOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VESTIBULARCURSOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VESTIBULARCURSO');
    }


    public function getVestibularesAbertos() {
         $q = $this->createQuery('a')          
          ->innerJoin('a.VESTIBULAR b')
          ->where('b.sg_situacao="A"');
        
        return $q->execute();
    }
    public function getCursosDoVestibular($id_vestibular) {
         $q = $this->createQuery('v')
          ->leftJoin('v.CURSO c')
          ->where('v.id_vestibular = ?', $id_vestibular);
         

    return $q->execute();
  }






    
}