CURSO:
  connection: doctrine
  tableName: CURSO
  columns:
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nm_curso:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    te_cargahoraria:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sg_flag:
      type: string(2)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
INSCRICAO:
  connection: doctrine
  tableName: INSCRICAO
  columns:
    id_inscricao:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_vestibular_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    id_sala:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nm_vestibulando:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    te_endereco:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_numero:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_cpf:
      type: string(11)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    te_complemento:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    te_bairro:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sg_estado:
      type: string(2)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    te_cidade:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_fone:
      type: string(12)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    te_resultado:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_pontuacao:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    dt_inscricao:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    SALA: { onDelete: CASCADE, local: id_sala, foreign: id_sala}
    VESTIBULARCURSO: { onDelete: CASCADE, local: id_vestibular_curso, foreign: id_vestibular_curso}
INSTITUICAO:
  connection: doctrine
  tableName: INSTITUICAO
  columns:
    id_instituicao:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nm_instituicao:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    te_endereco:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_numero:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    te_complemento:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    te_bairro:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    te_cidade:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sg_estado:
      type: string(2)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_cnpj:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_fone:
      type: string(15)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
SALA:
  connection: doctrine
  tableName: SALA
  columns:
    id_sala:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nm_sala:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    qt_max_suportada:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
VESTIBULAR:
  connection: doctrine
  tableName: VESTIBULAR
  columns:
    id_vestibular:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    te_periodo:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    te_horario:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    dt_vestibular:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sg_situacao:
      type: string(2)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sg_flag:
      type: string(2)
      fixed: true
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
VESTIBULARCURSO:
  connection: doctrine
  tableName: VESTIBULARCURSO
  columns:
    id_vestibular_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_vestibular:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nu_concorrencia:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    qt_vagas:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_pontuacao:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nu_inscritos:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    VESTIBULAR: { onDelete: CASCADE, local: id_vestibular, foreign: id_vestibular}
    CURSO: { onDelete: CASCADE, local: id_curso, foreign: id_curso}

